### PR TITLE
Add support for formatting range (textDocument/rangeFormatting).

### PR DESCRIPTION
**Pull request by kristijanhusak**

### CODE REVIEW

**Comment by DonnieWest** [comment]
Planning on reviewing this soon(ish) and getting it merged in. Just FYI :+1:

**Comment by DonnieWest** [comment]
Thanks for the PR

**Comment by kristijanhusak** [comment]
@DonnieWest any chance to get new release out?

**Comment by DonnieWest** [comment]
I'm planning to pull in a few other things before I cut a new release :)

**Pull request merged**
